@startuml

	left to right direction

	actor Actor as act
	actor Customer as cst

	cst --> (Read Blog post)

	act --> (Write new Article)
	act --> (Delete Article with ID)
	act --> (Read Blog post)
@enduml